platform :ios,  '7.0'

pod 'AFNetworking', '~> 2.1.0'
pod "MagicalRecord", '~> 2.2'
pod 'KeepLayout', '~> 1.2.2'
pod 'PonyDebugger', '~> 0.3.0', :inhibit_warnings => true
pod 'DCIntrospect-ARC', '~> 0.0.6', :inhibit_warnings => true
